# Generated by Django 3.2.12 on 2022-05-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posthog", "0232_add_team_person_display_name_properties"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedAsset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("image/png", "image/png"),
                            ("application/pdf", "application/pdf"),
                            ("text/csv", "text/csv"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.BinaryField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posthog.dashboard"),
                ),
                (
                    "insight",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posthog.insight"),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
            ],
        ),
    ]
